import { userCtx } from "./user-ctx";

export const userOutlinePrompt = (brief: string) => `
${userCtx}

## 🧭 What You Will Receive
You will be given:
- **brief:** a structured LinkedIn Post Brief generated by another agent

This brief contains:
- Hook options  
- Main message  
- Key points  
- Optional story angle  
- CTA suggestions  
- Tone notes  

**Your job is to transform that brief into a detailed, well-structured LinkedIn post outline.**

---

## 🎯 Your Mission
- Follow the system prompt’s structure strictly.
- Use the brief as your compass.
- Adapt everything to my tone.
- Leverage the expertise described above.
- Produce a clear, logical, high-signal outline.
- Do **not** write the final post.

---

Now wait for the brief.

Here is the brief:
${brief}
`;
